// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ...


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdBfRghXDuMZRIH2z7sslPRxbjDJw2-ME',
    appId: '1:669983599993:web:9bfba14dfe6e1aae2ad3a8',
    messagingSenderId: '669983599993',
    projectId: 'piggyplanner-mobile',
    authDomain: 'piggyplanner-mobile.firebaseapp.com',
    storageBucket: 'piggyplanner-mobile.appspot.com',
    measurementId: 'G-HNLMDCVSLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL7UyKQEVf9JF35lcckS0IA5IlVZ6fVAc',
    appId: '1:669983599993:android:af17dfc575e0da3f2ad3a8',
    messagingSenderId: '669983599993',
    projectId: 'piggyplanner-mobile',
    storageBucket: 'piggyplanner-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuS51dJlBWpC0XFqzrEFL_oSA9izODSoo',
    appId: '1:669983599993:ios:b8e010d46b0359e32ad3a8',
    messagingSenderId: '669983599993',
    projectId: 'piggyplanner-mobile',
    storageBucket: 'piggyplanner-mobile.appspot.com',
    iosClientId: '669983599993-pb0mdu3rjv69c21m0c9qfmokm1shjo90.apps.googleusercontent.com',
    iosBundleId: 'com.example.piggyPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuS51dJlBWpC0XFqzrEFL_oSA9izODSoo',
    appId: '1:669983599993:ios:b8e010d46b0359e32ad3a8',
    messagingSenderId: '669983599993',
    projectId: 'piggyplanner-mobile',
    storageBucket: 'piggyplanner-mobile.appspot.com',
    iosClientId: '669983599993-pb0mdu3rjv69c21m0c9qfmokm1shjo90.apps.googleusercontent.com',
    iosBundleId: 'com.example.piggyPlanner',
  );
}
